# Generated by Django 6.0.2 on 2026-03-09 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_session_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='duration',
            field=models.PositiveIntegerField(default=60, help_text='Длительность в минутах'),
        ),
        migrations.AlterField(
            model_name='session',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='session',
            name='max_places',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='session',
            name='sport',
            field=models.CharField(choices=[('volleyball', 'Волейбол'), ('basketball', 'Баскетбол'), ('football', 'Футбол'), ('fitness', 'Фитнес')], max_length=20),
        ),
        migrations.CreateModel(
            name='RecurringSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(choices=[('volleyball', 'Волейбол'), ('basketball', 'Баскетбол'), ('football', 'Футбол'), ('fitness', 'Фитнес')], max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('weekday', models.IntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')])),
                ('time', models.TimeField()),
                ('duration', models.PositiveIntegerField(default=60)),
                ('max_places', models.PositiveIntegerField(default=15)),
                ('date_from', models.DateField(help_text='С какой даты начинать генерацию')),
                ('date_until', models.DateField(blank=True, help_text='До какой даты (пусто = без конца, генерируем на 8 недель вперёд)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('coach', models.ForeignKey(limit_choices_to={'role': 'coach'}, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Шаблон тренировки',
                'verbose_name_plural': 'Шаблоны тренировок',
            },
        ),
        migrations.AddField(
            model_name='session',
            name='recurring',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='main.recurringsession'),
        ),
    ]
