# Generated by Django 6.0.2 on 2026-03-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringsession',
            name='repeat_mode',
            field=models.CharField(choices=[('weekly', 'Еженедельно'), ('daily', 'Ежедневно')], default='weekly', max_length=10),
        ),
        migrations.AlterField(
            model_name='recurringsession',
            name='weekday',
            field=models.IntegerField(blank=True, choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], null=True),
        ),
    ]
